import { Geist, Geist_Mono, Poppins } from "next/font/google";
import RootLayout from "./RootLayout";  // The client-side logic will be handled here
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "600", "700"], // adjust as needed
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        {/* Pass the children to the RootLayout component */}
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  );
}
